"""your message

Revision ID: f2011a9b90c1
Revises: 8eaff33eeaa4
Create Date: 2024-10-14 10:49:39.035444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2011a9b90c1'
down_revision = '8eaff33eeaa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
